### ISSUE TITLE
still bark til night

### ISSUE THREAD

**Issue by livibetter** [alexdantas/doge-toe#1]
When one dog wins, the game doesn't force a reset, you can still click, and score is still being counted.

I honestly don't know if this is a bug or by intention since this is Doge, they probably just want to have more fun.

(night = nine)

**Comment by alexdantas** [comment]
You never stop surprising me, dear friend :laughing:

That was a bug alright... And a very serious one.
Just imagine how many people cheated when the other competitor wasn't looking!

It should be fixed by tomorrow night.

**Comment by livibetter** [comment]
Something like this [quiet snatch](http://youtu.be/3lJ06QROBXs) or this [simple bruteforce](http://youtu.be/fdI6Qt0_h1w)?

_Kid v. Doge = 1:1, who win so epic Doge-toe top Doge-boy? Sit tuned, we is fast back many hip wow._

**Comment by alexdantas** [comment]
:joy::joy::joy:
Oh my god, couldn't stop laughing - the kid's face on that bruteforce attack!

that was :dog2: + :trollface:
